default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    match(type: 'appstore', readonly: true)
    increment_build_number(xcodeproj: "SpaceCompany.xcodeproj")
    gym(workspace: "SpaceCompany.xcworkspace", scheme: "SpaceCompany", export_method: "app-store", export_xcargs: "-allowProvisioningUpdates")
    testflight(
      changelog: 'Auto-distributed build, github integration pending', 
      distribute_external: true, 
      groups:['discord'],
    )
  end
end
