default_platform(:ios)

platform :ios do
  lane :setBuildNumber do
    increment_build_number(
      build_number: Time.now.strftime("%Y.%m.%d.%H%M%S")
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    setBuildNumber
    match(type: 'appstore', readonly: true)
    gym(workspace: "SpaceCompany.xcworkspace", scheme: "SpaceCompany", export_method: "app-store", export_xcargs: "-allowProvisioningUpdates")
    testflight(
      skip_waiting_for_build_processing: true

      # Stopped auto-distribution to externals due to fastlane 2fa bug
      # changelog: 'Auto-distributed build, github integration pending', 
      # distribute_external: true, 
      # groups:['Discord', 'Patreon'],
    )
  end
end
